In [1]:
#libraries
import pandas as pd

In [3]:
#read data
df = pd.read_csv('credit_data.csv')
print(df.shape)

(32581, 12)

In [4]:
df.head()

,age,income,home_ownership,employment_length,loan_intent,loan_grade,loan_amount,interest_rate,loan_status,loan_percent_income,historical_default,cred_hist_length
0,22,59000,RENT,123,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [5]:
#info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  32581 non-null  int64
 1   income               32581 non-null  int64
 2   home_ownership       32581 non-null  str
 3   employment_length    32581 non-null  str
 4   loan_intent          32581 non-null  str
 5   loan_grade           32581 non-null  str
 6   loan_amount          32581 non-null  int64
 7   interest_rate        32581 non-null  str
 8   loan_status          32581 non-null  int64
 9   loan_percent_income  32581 non-null  float64
 10  historical_default   32581 non-null  str
 11  cred_hist_length     32581 non-null  int64
dtypes: float64(1), int64(5), str(6)
memory usage: 3.0 MB

In [6]:
#descriptive statistics
df.describe()

,age,income,loan_amount,loan_status,loan_percent_income,cred_hist_length
count,32581.000000,3.258100e+04,32581.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,9589.371106,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,6322.086646,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,500.000000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,5000.000000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,8000.000000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,12200.000000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,35000.000000,1.000000,0.830000,30.000000

In [8]:
# descriptive statistics for categorical variables
df.describe(include='string')

,home_ownership,employment_length,loan_intent,loan_grade,interest_rate,historical_default
count,32581,32581,32581,32581,32581,32581
unique,4,37,6,7,349,2
top,RENT,0,EDUCATION,A,?,N
freq,16446,4105,6453,10777,3116,26836

In [9]:
# null values
df.isnull().sum()

age                    0
income                 0
home_ownership         0
employment_length      0
loan_intent            0
loan_grade             0
loan_amount            0
interest_rate          0
loan_status            0
loan_percent_income    0
historical_default     0
cred_hist_length       0
dtype: int64

# EDA